-- Migracion orientativa del modulo de facturas SaaS de Membora.
-- La aplicacion ejecuta migraciones compatibles desde PlatformInvoiceRepository::ensureTable().

CREATE TABLE IF NOT EXISTS platform_invoices (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  empresa_id VARCHAR(191) NOT NULL,
  payment_id VARCHAR(191) NULL,
  invoice_series VARCHAR(32) NOT NULL,
  invoice_number INT NULL,
  invoice_code VARCHAR(64) NULL,
  invoice_type VARCHAR(32) NOT NULL DEFAULT 'ORDINARY',
  invoice_status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  collection_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  issued_at DATE NOT NULL,
  operation_at DATE NULL,
  period_start_at DATE NULL,
  period_end_at DATE NULL,
  due_at DATE NULL,
  issuer_name VARCHAR(191) NULL,
  issuer_tax_id VARCHAR(64) NULL,
  issuer_address VARCHAR(255) NULL,
  issuer_postal_code VARCHAR(32) NULL,
  issuer_city VARCHAR(120) NULL,
  issuer_province VARCHAR(120) NULL,
  issuer_country VARCHAR(120) NULL,
  issuer_email VARCHAR(191) NULL,
  issuer_phone VARCHAR(64) NULL,
  customer_name VARCHAR(191) NULL,
  customer_tax_id VARCHAR(64) NULL,
  customer_address VARCHAR(255) NULL,
  customer_postal_code VARCHAR(32) NULL,
  customer_city VARCHAR(120) NULL,
  customer_province VARCHAR(120) NULL,
  customer_country VARCHAR(120) NULL,
  customer_email VARCHAR(191) NULL,
  customer_phone VARCHAR(64) NULL,
  concept VARCHAR(191) NOT NULL,
  subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxable_base DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_breakdown TEXT NULL,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 21.00,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  pending_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
  payment_method VARCHAR(64) NOT NULL DEFAULT 'TRANSFER',
  fiscal_treatment VARCHAR(64) NOT NULL DEFAULT 'VAT_SUBJECT',
  fiscal_note TEXT NULL,
  public_notes TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ISSUED',
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY platform_invoices_empresa_series_number_unique (empresa_id, invoice_series, invoice_number),
  INDEX platform_invoices_empresa_idx (empresa_id),
  INDEX platform_invoices_invoice_status_idx (invoice_status),
  INDEX platform_invoices_collection_status_idx (collection_status)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_invoice_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  invoice_id VARCHAR(191) NOT NULL,
  description VARCHAR(255) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 1,
  unit VARCHAR(32) NOT NULL DEFAULT 'ud',
  unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_type VARCHAR(16) NOT NULL DEFAULT 'PERCENT',
  discount_value DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxable_base DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 21.00,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX platform_invoice_items_invoice_idx (invoice_id),
  INDEX platform_invoice_items_order_idx (invoice_id, sort_order)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_invoice_payments (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  invoice_id VARCHAR(191) NOT NULL,
  paid_at DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_method VARCHAR(64) NOT NULL DEFAULT 'TRANSFER',
  reference VARCHAR(191) NULL,
  notes TEXT NULL,
  attachment_path VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX platform_invoice_payments_invoice_idx (invoice_id),
  INDEX platform_invoice_payments_paid_idx (paid_at)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
