ALTER TABLE subscriptions
  ADD COLUMN IF NOT EXISTS next_billing_at DATE NULL;

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS period_start_at DATE NULL,
  ADD COLUMN IF NOT EXISTS period_end_at DATE NULL,
  ADD COLUMN IF NOT EXISTS reference VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS paid_notes TEXT NULL;
